name: Go CI
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: go build ./...
      - name: Run Tests
        run: go test ./... -v
      - name: Vet
        run: go vet ./...
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
  benchmark:
    name: Benchmarks
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run Benchmarks
        run: make benchmark ARGS='-bench=. -cpu=1' > bench.txt
      - name: Commit benchmark result
        run: |
          if [ -f bench.txt ]; then \
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add bench.txt
            git commit -m "Update benchmark results [skip ci]" || echo "No changes to commit"
            git push
          else
            echo "bench.txt not found"
            exit 1
          fi
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: bench.txt
